import { Tenant } from '../models/tenant.model';

/**
 * Optional store for multi-tenant applications.
 *
 * Implement this interface when your application serves multiple independent
 * tenants (organisations, workspaces, teams, etc.) and you need to isolate
 * users, data, and configuration per tenant.
 *
 * The interface covers three concerns:
 *  1. **Tenant CRUD** — create, read, update and delete tenants.
 *  2. **User ↔ Tenant association** — which users belong to which tenant.
 *  3. **Per-tenant auth config** — optional overrides such as allowed auth
 *     methods, custom OAuth clients, or token lifetimes per tenant.
 *
 * @example
 * ```typescript
 * import { ITenantStore } from 'awesome-node-auth';
 *
 * export class MyTenantStore implements ITenantStore {
 *   async createTenant(data) {
 *     const id = slugify(data.name);
 *     await db('tenants').insert({ id, ...data });
 *     return { id, ...data };
 *   }
 *   async getTenantById(id) {
 *     return db('tenants').where({ id }).first() ?? null;
 *   }
 *   async getAllTenants() {
 *     return db('tenants').select();
 *   }
 *   async updateTenant(id, data) {
 *     await db('tenants').where({ id }).update(data);
 *   }
 *   async deleteTenant(id) {
 *     await db('tenants').where({ id }).delete();
 *   }
 *   async associateUserWithTenant(userId, tenantId) {
 *     await db('tenant_users').insert({ userId, tenantId });
 *   }
 *   async disassociateUserFromTenant(userId, tenantId) {
 *     await db('tenant_users').where({ userId, tenantId }).delete();
 *   }
 *   async getTenantsForUser(userId) {
 *     return db('tenant_users').join('tenants', ...).where({ userId });
 *   }
 *   async getUsersForTenant(tenantId) {
 *     return db('tenant_users').where({ tenantId }).pluck('userId');
 *   }
 * }
 * ```
 */
export interface ITenantStore {
  // ------------------------------------------------------------------
  // Tenant CRUD
  // ------------------------------------------------------------------

  /**
   * Create a new tenant.  The `id` is generated by the implementation
   * (e.g. a UUID or a URL-safe slug derived from `name`).
   */
  createTenant(data: Omit<Tenant, 'id'>): Promise<Tenant>;

  /**
   * Fetch a tenant by its unique identifier.
   * Returns `null` when no tenant with that ID exists.
   */
  getTenantById(id: string): Promise<Tenant | null>;

  /**
   * Return all tenants.  For large deployments consider adding pagination
   * in your own implementation.
   */
  getAllTenants(): Promise<Tenant[]>;

  /**
   * Partially update a tenant's fields.
   * Only the fields present in `data` are changed.
   */
  updateTenant(id: string, data: Partial<Omit<Tenant, 'id'>>): Promise<void>;

  /**
   * Permanently delete a tenant and all its associated data.
   * This should also remove all user ↔ tenant associations for the tenant.
   */
  deleteTenant(id: string): Promise<void>;

  // ------------------------------------------------------------------
  // User ↔ Tenant membership
  // ------------------------------------------------------------------

  /**
   * Add `userId` as a member of `tenantId`.
   * Idempotent — calling it when the association already exists should not throw.
   */
  associateUserWithTenant(userId: string, tenantId: string): Promise<void>;

  /**
   * Remove `userId` from `tenantId`.
   * No-op when the association does not exist.
   */
  disassociateUserFromTenant(userId: string, tenantId: string): Promise<void>;

  /**
   * Return all tenants the given user belongs to.
   */
  getTenantsForUser(userId: string): Promise<Tenant[]>;

  /**
   * Return the IDs of all users that belong to the given tenant.
   */
  getUsersForTenant(tenantId: string): Promise<string[]>;
}
